import type { Metadata } from "next";
import "./globals.css";
import { getMessages, getLocale } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";
import { GIUTSLanguage, giUTSLanguages } from "@repo/gi-data/languages";
import SideBar from "@/components/sidebar";
import Footer from "@/components/footer";
import { Analytics } from "@vercel/analytics/next";
import { SpeedInsights } from "@vercel/speed-insights/next";
// import LocaleSwitcher from "@/components/locale-switcher";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  if (!giUTSLanguages.includes(locale as GIUTSLanguage)) {
    notFound();
  }
  const messages = await getMessages();
  return (
    <html lang={locale}>
      <body className="antialiased m-0 flex min-h-full flex-col p-0">
        <NextIntlClientProvider messages={messages}>
          <div className="flex min-h-screen flex-col">
            <SideBar />
            {children}
            <Footer />
          </div>
        </NextIntlClientProvider>
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
