import type { Metadata } from "next";
import "./globals.css";
import { getMessages, getLocale } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";
import { GIUTSLanguage, giUTSLanguages } from "@repo/gi-data/languages";
// import LocaleSwitcher from "@/components/locale-switcher";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  if (!giUTSLanguages.includes(locale as GIUTSLanguage)) {
    notFound();
  }
  const messages = await getMessages();
  return (
    <html lang={locale}>
      <body className="antialiased">
        <NextIntlClientProvider messages={messages}>
          {/* <header className="flex flex-row gap-4">
            <nav></nav>
            <LocaleSwitcher className="ml-auto" />
          </header> */}
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
