import { existsSync, readdirSync, readFileSync } from "fs";
import path from "path";
import JsonToTS from "json-to-ts";
import { writeFileSyncRecursive } from "@repo/utils/fs";
import { pascalCaseToKebabCase } from "@repo/utils/pascal-to-kebab";

const APP_ROOT = path.resolve(".");
const MONOREPO_ROOT = path.resolve(APP_ROOT, "..", "..");
const REPO_ROOT = path.join(MONOREPO_ROOT, "packages", "gi-data");
const GI_DM_ROOT = path.join(REPO_ROOT, "AnimeGameData");
const EBO = path.join(GI_DM_ROOT, "ExcelBinOutput");

const getEBOFilePath = (fileName: string) => path.join(EBO, fileName);

const getEBOFileContent = (fileName: string) => {
  const filePath = getEBOFilePath(fileName);
  if (!existsSync(filePath)) throw `File not found :${filePath}`;
  return readFileSync(filePath).toString();
};

const getParsedEBOFile = (fileName: string) => {
  return JSON.parse(getEBOFileContent(fileName));
};

// Learn more about Turborepo Generators at https://turbo.build/repo/docs/core-concepts/monorepos/code-generation

const main = async () => {
  let EBOJsonFiles: string[] = [];
  try {
    EBOJsonFiles = readdirSync(EBO).filter((f) => path.extname(f) === ".json");
  } catch (error) {
    console.log(error);
  }
  for (const jsonFileName of EBOJsonFiles) {
    const strippedFileName = path.parse(jsonFileName).name;
    const typeName = strippedFileName.endsWith("ExcelConfigData")
      ? strippedFileName.slice(0, -"ExcelConfigData".length)
      : strippedFileName;
    let content: string = "";
    try {
      content = getEBOFileContent(jsonFileName);
    } catch (error) {
      console.error(error);
    }
    const jsonContent = JSON.parse(content);
    const isArray = Array.isArray(jsonContent);
    let lines: string[] = [];
    try {
      lines = JsonToTS(jsonContent, {
        useTypeAlias: true,
      });
    } catch (error) {
      console.error(error);
    }
    const typeFileLines = [
      `// generated by gi-data-types for \`${jsonFileName}\``,
      `import { readDMJSON } from "../../util.js";`,
      lines.join("\n"),
      `export default JSON.parse(readDMJSON("ExcelBinOutput/${JSON.stringify(jsonFileName).slice(1, -1)}"))${lines.length === 0 ? "" : ` as RootObject${isArray ? "[]" : ""}`}`,
    ];
    const typeFileContent = typeFileLines.join("\n");
    const typeFileLocation = path.join(
      REPO_ROOT,
      "src",
      "generated",
      "excel-bin-output",
      `${pascalCaseToKebabCase(typeName)}.ts`
    );
    writeFileSyncRecursive(typeFileLocation, typeFileContent);
    console.log(`Write to "${typeFileLocation} was successful..."`);
  }

  return "Finished generating types!";
};

main();
