import {
  getCharacterInfos,
  getAvatarCurves,
  getAvatarPromoteInfo,
} from "@repo/gi-data/generators/character";
import { writeFileSync } from "fs";
import path from "path";

const APP_ROOT = path.resolve(".");
const MONOREPO_ROOT = path.resolve(APP_ROOT, "..", "..");
const GI_DATA_ROOT = path.join(MONOREPO_ROOT, "packages", "gi-data");
const GI_DATA_EXPORTS = path.join(GI_DATA_ROOT, "src", "generated");

const { relevantHashes, ...restOfCharacterInfo } = getCharacterInfos();
const characterInfo = {
  ...restOfCharacterInfo,
  relevantHashes: [...relevantHashes],
};
const characterInfoStr = JSON.stringify(characterInfo, null, 2);

const characterStatCurves = getAvatarCurves();
const characterStatCurvesStr = JSON.stringify(characterStatCurves, null, 2);

const characterAscensionInfo = getAvatarPromoteInfo();
const characterAscensionInfoStr = JSON.stringify(
  characterAscensionInfo,
  null,
  2
);

// character-info.ts
const characterInfoLines = [
  "// generated by gen-gi-data",
  `export const characterInfo = ${characterInfoStr};`,
  `export const characterStatCurves = ${characterStatCurvesStr};`,
  `export const characterAscensionInfo = ${characterAscensionInfoStr};`,
];
const characterInfoContents = characterInfoLines.join("\n");
const characterInfoPath = path.join(GI_DATA_EXPORTS, "character-info.ts");

writeFileSync(characterInfoPath, characterInfoContents);
console.log(`Write to "${characterInfoPath} was successful...`);
