import {
  getCharacterInfos,
  getAvatarCurves,
  getAvatarPromoteInfo,
} from "@repo/gi-data/generators/character";
import {
  getWeaponInfos,
  getWeaponCurves,
  getWeaponPromoteInfo,
} from "@repo/gi-data/generators/weapon";
import { writeFileSync } from "fs";
import path from "path";

const APP_ROOT = path.resolve(".");
const MONOREPO_ROOT = path.resolve(APP_ROOT, "..", "..");
const GI_DATA_ROOT = path.join(MONOREPO_ROOT, "packages", "gi-data");
const GI_DATA_EXPORTS = path.join(GI_DATA_ROOT, "src", "generated");

const { relevantHashes: characterRelHashes, ...restOfCharacterInfo } =
  getCharacterInfos();
const characterInfo = {
  ...restOfCharacterInfo,
  relevantHashes: [...characterRelHashes],
};
const characterInfoStr = JSON.stringify(characterInfo, null, 2);

const characterStatCurves = getAvatarCurves();
const characterStatCurvesStr = JSON.stringify(characterStatCurves, null, 2);

const characterAscensionInfo = getAvatarPromoteInfo();
const characterAscensionInfoStr = JSON.stringify(
  characterAscensionInfo,
  null,
  2
);

const { relevantHashes: weaponRelHashes, ...restOfWeaponInfo } =
  getWeaponInfos();
const weaponInfo = {
  ...restOfWeaponInfo,
  relevantHashes: [...weaponRelHashes],
};
const weaponInfoStr = JSON.stringify(weaponInfo, null, 2);

const weaponStatCurves = getWeaponCurves();
const weaponStatCurvesStr = JSON.stringify(weaponStatCurves, null, 2);

const weaponAscensionInfo = getWeaponPromoteInfo();
const weaponAscensionInfoStr = JSON.stringify(weaponAscensionInfo, null, 2);

// character-info.ts
const characterInfoLines = [
  "// generated by gen-gi-data",
  `export const characterInfo = ${characterInfoStr};`,
  `export const characterStatCurves = ${characterStatCurvesStr};`,
  `export const characterAscensionInfo = ${characterAscensionInfoStr};`,
];
const characterInfoContents = characterInfoLines.join("\n");
const characterInfoPath = path.join(GI_DATA_EXPORTS, "character-info.ts");

writeFileSync(characterInfoPath, characterInfoContents);
console.log(`Write to "${characterInfoPath}" was successful...`);

// weapon-info.ts
const weaponInfoLines = [
  "// generated by gen-gi-data",
  `export const weaponInfo = ${weaponInfoStr};`,
  `export const weaponStatCurves = ${weaponStatCurvesStr};`,
  `export const weaponAscensionInfo = ${weaponAscensionInfoStr};`,
];
const weaponInfoContents = weaponInfoLines.join("\n");
const weaponInfoPath = path.join(GI_DATA_EXPORTS, "weapon-info.ts");

writeFileSync(weaponInfoPath, weaponInfoContents);
console.log(`Write to "${weaponInfoPath}" was successful...`);
